import { Trade } from '../types/trade';

// Demo sample trades to illustrate dashboard metrics when user clicks "Load Demo Data"
export const DEMO_TRADES: Trade[] = [
  {
    id: 'TRD-001',
    date: '2026-09-01',
    time: '08:30',
    pair: 'EURUSD',
    direction: 'BUY',
    timeframe: 'M15',
    session: 'LONDON',
    setup: 'EMA 9/21 Pullback',
    marketCondition: 'TRENDING',
    entry: 1.08500,
    stopLoss: 1.08350,
    takeProfit: 1.08800,
    exit: 1.08800,
    riskPercent: 1.0,
    riskAmount: 3.0,
    rrPlanned: 2.0,
    rrActual: 2.0,
    result: 'WIN',
    resultR: 2.0,
    profitLoss: 6.0,
    duration: '1h 15m',
    screenshotUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=60',
    screenshots: [
      {
        id: 'sc-1',
        name: 'TRD-001_2026-09-01_EURUSD_ENTRY.png',
        url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=60',
        type: 'entry',
      },
    ],
    entryReason: 'Valid pullback ke EMA 21 setelah break high sesi Asia. Bullish rejection candle pada M15.',
    marketContext: 'Strong bullish trend pada H1 dan D1, market trending teratur tanpa berita high impact.',
    confirmation: 'Bullish engulfing candle pada zone support 1.08500.',
    mistake: '-',
    emotion: 'Tenang, menunggu close candle sesuai SOP.',
    lesson: 'Disiplin menunggu confluence EMA dan key support memberikan hasil bersih.',
    tags: ['#goodsetup', '#cleanexecution', '#ema'],
    executedToPlan: true,
    planViolation: false,
    backtestSessionId: 'BT-2026-09-01-01',
    accountId: 'Backtest Account',
    isDemo: true,
    createdAt: '2026-09-01T08:30:00Z',
  },
  {
    id: 'TRD-002',
    date: '2026-09-02',
    time: '14:15',
    pair: 'GBPUSD',
    direction: 'SELL',
    timeframe: 'M5',
    session: 'NEW YORK',
    setup: 'Liquidity Sweep',
    marketCondition: 'HIGH VOLATILITY',
    entry: 1.27200,
    stopLoss: 1.27350,
    takeProfit: 1.26800,
    exit: 1.26750,
    riskPercent: 1.0,
    riskAmount: 3.0,
    rrPlanned: 2.67,
    rrActual: 3.0,
    result: 'WIN',
    resultR: 3.0,
    profitLoss: 9.0,
    duration: '45m',
    screenshotUrl: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&auto=format&fit=crop&q=60',
    screenshots: [
      {
        id: 'sc-2',
        name: 'TRD-002_2026-09-02_GBPUSD_SWEEP.png',
        url: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&auto=format&fit=crop&q=60',
        type: 'entry',
      },
    ],
    entryReason: 'Sweep previous high sesi London lalu terjadi change of character (CHoCH) cepat.',
    marketContext: 'Volatilitas tinggi menjelang pembukaan ekuitas New York.',
    confirmation: 'Fair value gap terbentuk setelah sweep, limit order terisi.',
    mistake: '-',
    emotion: 'Percaya diri pada setup liquidity sweep.',
    lesson: 'Timing sweep saat overlap sesi sangat powerful.',
    tags: ['#liquiditysweep', '#newyork', '#perfectsetup'],
    executedToPlan: true,
    planViolation: false,
    backtestSessionId: 'BT-2026-09-01-01',
    accountId: 'Backtest Account',
    isDemo: true,
    createdAt: '2026-09-02T14:15:00Z',
  },
  {
    id: 'TRD-003',
    date: '2026-09-03',
    time: '09:00',
    pair: 'XAUUSD',
    direction: 'BUY',
    timeframe: 'M5',
    session: 'LONDON',
    setup: 'Breakout',
    marketCondition: 'TRENDING',
    entry: 2450.00,
    stopLoss: 2444.00,
    takeProfit: 2465.00,
    exit: 2444.00,
    riskPercent: 1.0,
    riskAmount: 3.0,
    rrPlanned: 2.5,
    rrActual: -1.0,
    result: 'LOSS',
    resultR: -1.0,
    profitLoss: -3.0,
    duration: '20m',
    screenshotUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=60',
    screenshots: [],
    entryReason: 'Mencoba entry breakout consolidation range pagi hari.',
    marketContext: 'Gold bergerak lambat sebelum berita PMI.',
    confirmation: 'Candle break resistance tapi gagal hold.',
    mistake: 'Entry terlalu terburu-buru sebelum ada retest valid.',
    emotion: 'Sedikit FOMO karena takut tertinggal rally.',
    lesson: 'Jangan entry breakout langsung di Gold tanpa konfirmasi volume retest.',
    tags: ['#fomo', '#breakout', '#lateentry'],
    executedToPlan: false,
    planViolation: true,
    planViolationReason: 'Entry breakout tanpa menunggu retest sesuai SOP',
    backtestSessionId: 'BT-2026-09-01-01',
    accountId: 'Backtest Account',
    isDemo: true,
    createdAt: '2026-09-03T09:00:00Z',
  },
  {
    id: 'TRD-004',
    date: '2026-09-04',
    time: '15:30',
    pair: 'USDJPY',
    direction: 'SELL',
    timeframe: 'M15',
    session: 'NEW YORK',
    setup: 'Structure Break',
    marketCondition: 'TRENDING',
    entry: 145.800,
    stopLoss: 146.100,
    takeProfit: 145.200,
    exit: 145.200,
    riskPercent: 1.0,
    riskAmount: 3.0,
    rrPlanned: 2.0,
    rrActual: 2.0,
    result: 'WIN',
    resultR: 2.0,
    profitLoss: 6.0,
    duration: '2h',
    screenshotUrl: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&auto=format&fit=crop&q=60',
    screenshots: [],
    entryReason: 'Break of structure lower low pada M15, retest order block.',
    marketContext: 'DXY mengalami pelemahan teratur.',
    confirmation: 'Bearish pinbar di level 145.800.',
    mistake: '-',
    emotion: 'Sangat sabar menunggu pullback.',
    lesson: 'Struktur M15 sangat akurat pada USDJPY.',
    tags: ['#structurebreak', '#usdjpy'],
    executedToPlan: true,
    planViolation: false,
    backtestSessionId: 'BT-2026-09-01-01',
    accountId: 'Backtest Account',
    isDemo: true,
    createdAt: '2026-09-04T15:30:00Z',
  },
  {
    id: 'TRD-005',
    date: '2026-09-07',
    time: '02:00',
    pair: 'USDJPY',
    direction: 'BUY',
    timeframe: 'M30',
    session: 'ASIA',
    setup: 'Support Resistance',
    marketCondition: 'RANGING',
    entry: 144.500,
    stopLoss: 144.250,
    takeProfit: 145.100,
    exit: 144.500,
    riskPercent: 1.0,
    riskAmount: 3.0,
    rrPlanned: 2.4,
    rrActual: 0.0,
    result: 'BE',
    resultR: 0.0,
    profitLoss: 0.0,
    duration: '3h',
    screenshotUrl: '',
    screenshots: [],
    entryReason: 'Bounce dari major support H4 di sesi Asia.',
    marketContext: 'Range market sempit khas Tokyo session.',
    confirmation: 'Dua kali reject support dengan long wick.',
    mistake: '-',
    emotion: 'Netral.',
    lesson: 'SL dipindah ke BE setelah running +1R, pasar berbalik dan terkena BE.',
    tags: ['#ranging', '#asia', '#breakeven'],
    executedToPlan: true,
    planViolation: false,
    backtestSessionId: 'BT-2026-09-07-01',
    accountId: 'Backtest Account',
    isDemo: true,
    createdAt: '2026-09-07T02:00:00Z',
  },
  {
    id: 'TRD-006',
    date: '2026-09-08',
    time: '08:45',
    pair: 'XAUUSD',
    direction: 'BUY',
    timeframe: 'M5',
    session: 'LONDON',
    setup: 'Liquidity Sweep',
    marketCondition: 'HIGH VOLATILITY',
    entry: 2470.50,
    stopLoss: 2465.00,
    takeProfit: 2485.00,
    exit: 2484.50,
    riskPercent: 1.0,
    riskAmount: 3.0,
    rrPlanned: 2.64,
    rrActual: 2.55,
    result: 'WIN',
    resultR: 2.55,
    profitLoss: 7.65,
    duration: '50m',
    screenshotUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=60',
    screenshots: [],
    entryReason: 'Sweep Asian low sedalam 20 pips lalu impulsive bounce ke atas.',
    marketContext: 'Gold trend strongly bullish pada timeframe H4.',
    confirmation: 'Shift in market structure + FVG M1 retest.',
    mistake: '-',
    emotion: 'Eksekusi sangat tenang dan presisi.',
    lesson: 'Asian low sweep di London session pada gold probabilitasnya tinggi.',
    tags: ['#gold', '#liquiditysweep', '#london'],
    executedToPlan: true,
    planViolation: false,
    backtestSessionId: 'BT-2026-09-07-01',
    accountId: 'Backtest Account',
    isDemo: true,
    createdAt: '2026-09-08T08:45:00Z',
  },
  {
    id: 'TRD-007',
    date: '2026-09-09',
    time: '13:30',
    pair: 'EURUSD',
    direction: 'SELL',
    timeframe: 'M15',
    session: 'LONDON + NEW YORK',
    setup: 'EMA 9/21 Pullback',
    marketCondition: 'TRENDING',
    entry: 1.08900,
    stopLoss: 1.09050,
    takeProfit: 1.08600,
    exit: 1.08600,
    riskPercent: 1.0,
    riskAmount: 3.0,
    rrPlanned: 2.0,
    rrActual: 2.0,
    result: 'WIN',
    resultR: 2.0,
    profitLoss: 6.0,
    duration: '1h 40m',
    screenshotUrl: '',
    screenshots: [],
    entryReason: 'Bearish continuation pullback ke 21 EMA saat London/NY overlap.',
    marketContext: 'Trend D1 bearish, retest previous day low.',
    confirmation: 'Bearish pin bar di confluence resistance.',
    mistake: '-',
    emotion: 'Fokus.',
    lesson: 'Overlap session memberikan volume dorongan kuat.',
    tags: ['#ema', '#trendcontinuation', '#overlap'],
    executedToPlan: true,
    planViolation: false,
    backtestSessionId: 'BT-2026-09-07-01',
    accountId: 'Backtest Account',
    isDemo: true,
    createdAt: '2026-09-09T13:30:00Z',
  },
  {
    id: 'TRD-008',
    date: '2026-09-10',
    time: '10:00',
    pair: 'GBPUSD',
    direction: 'BUY',
    timeframe: 'M5',
    session: 'LONDON',
    setup: 'Reversal',
    marketCondition: 'CHOPPY',
    entry: 1.26500,
    stopLoss: 1.26350,
    takeProfit: 1.26900,
    exit: 1.26350,
    riskPercent: 1.0,
    riskAmount: 3.0,
    rrPlanned: 2.67,
    rrActual: -1.0,
    result: 'LOSS',
    resultR: -1.0,
    profitLoss: -3.0,
    duration: '35m',
    screenshotUrl: '',
    screenshots: [],
    entryReason: 'Mencoba menangkap bottom di pasar yang sideways.',
    marketContext: 'Market choppy menjelang release data CPI.',
    confirmation: 'Sinyal reversal lemah di M5 tanpa dukungan H1.',
    mistake: 'Trading di kondisi choppy market sebelum data penting.',
    emotion: 'Ingin buru-buru buka posisi.',
    lesson: 'Hindari entry reversal saat kondisi market choppy.',
    tags: ['#choppy', '#mistake', '#badrr'],
    executedToPlan: false,
    planViolation: true,
    planViolationReason: 'Entry di kondisi market choppy berlawanan SOP',
    backtestSessionId: 'BT-2026-09-07-01',
    accountId: 'Backtest Account',
    isDemo: true,
    createdAt: '2026-09-10T10:00:00Z',
  },
  {
    id: 'TRD-009',
    date: '2026-09-11',
    time: '14:00',
    pair: 'XAUUSD',
    direction: 'SELL',
    timeframe: 'M15',
    session: 'NEW YORK',
    setup: 'Structure Break',
    marketCondition: 'TRENDING',
    entry: 2480.00,
    stopLoss: 2486.00,
    takeProfit: 2465.00,
    exit: 2465.00,
    riskPercent: 1.0,
    riskAmount: 3.0,
    rrPlanned: 2.5,
    rrActual: 2.5,
    result: 'WIN',
    resultR: 2.5,
    profitLoss: 7.5,
    duration: '1h 10m',
    screenshotUrl: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&auto=format&fit=crop&q=60',
    screenshots: [],
    entryReason: 'Lower high terbentuk di M15 setelah gagal menembus ATH.',
    marketContext: 'Bearish divergence di RSI M15.',
    confirmation: 'Strong displacement candle ke bawah.',
    mistake: '-',
    emotion: 'Puas karena sabar menunggu retest.',
    lesson: 'Confluence divergence dan structure break sangat valid.',
    tags: ['#gold', '#structurebreak', '#divergence'],
    executedToPlan: true,
    planViolation: false,
    backtestSessionId: 'BT-2026-09-07-01',
    accountId: 'Backtest Account',
    isDemo: true,
    createdAt: '2026-09-11T14:00:00Z',
  },
  {
    id: 'TRD-010',
    date: '2026-09-14',
    time: '08:15',
    pair: 'EURUSD',
    direction: 'BUY',
    timeframe: 'M5',
    session: 'LONDON',
    setup: 'EMA 9/21 Pullback',
    marketCondition: 'TRENDING',
    entry: 1.08200,
    stopLoss: 1.08050,
    takeProfit: 1.08550,
    exit: 1.08550,
    riskPercent: 1.0,
    riskAmount: 3.0,
    rrPlanned: 2.33,
    rrActual: 2.33,
    result: 'WIN',
    resultR: 2.33,
    profitLoss: 7.0,
    duration: '55m',
    screenshotUrl: '',
    screenshots: [],
    entryReason: 'London open continuation dengan pullback ke 9 EMA.',
    marketContext: 'Bullish momentum sejak awal pagi.',
    confirmation: 'Bullish hammer di 9 EMA.',
    mistake: '-',
    emotion: 'Percaya diri.',
    lesson: 'Pola EMA Pullback konsisten menghasilkan RR > 2.',
    tags: ['#ema', '#eurusd', '#london'],
    executedToPlan: true,
    planViolation: false,
    backtestSessionId: 'BT-2026-09-14-01',
    accountId: 'Backtest Account',
    isDemo: true,
    createdAt: '2026-09-14T08:15:00Z',
  },
  {
    id: 'TRD-011',
    date: '2026-09-15',
    time: '15:00',
    pair: 'XAUUSD',
    direction: 'BUY',
    timeframe: 'M5',
    session: 'NEW YORK',
    setup: 'Liquidity Sweep',
    marketCondition: 'TRENDING',
    entry: 2460.00,
    stopLoss: 2454.00,
    takeProfit: 2475.00,
    exit: 2475.00,
    riskPercent: 1.0,
    riskAmount: 3.0,
    rrPlanned: 2.5,
    rrActual: 2.5,
    result: 'WIN',
    resultR: 2.5,
    profitLoss: 7.5,
    duration: '1h 05m',
    screenshotUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=60',
    screenshots: [],
    entryReason: 'Sweep sell-side liquidity di awal sesi NY lalu agresif naik.',
    marketContext: 'Bullish continuation pada H1.',
    confirmation: 'M1 break of structure dan order block retest.',
    mistake: '-',
    emotion: 'Fokus penuh.',
    lesson: 'Liquidity sweep di Gold New York session sangat bersih.',
    tags: ['#gold', '#liquiditysweep', '#newyork'],
    executedToPlan: true,
    planViolation: false,
    backtestSessionId: 'BT-2026-09-14-01',
    accountId: 'Backtest Account',
    isDemo: true,
    createdAt: '2026-09-15T15:00:00Z',
  },
  {
    id: 'TRD-012',
    date: '2026-09-16',
    time: '09:30',
    pair: 'GBPUSD',
    direction: 'SELL',
    timeframe: 'M15',
    session: 'LONDON',
    setup: 'Breakout',
    marketCondition: 'TRENDING',
    entry: 1.27500,
    stopLoss: 1.27700,
    takeProfit: 1.27000,
    exit: 1.27700,
    riskPercent: 1.0,
    riskAmount: 3.0,
    rrPlanned: 2.5,
    rrActual: -1.0,
    result: 'LOSS',
    resultR: -1.0,
    profitLoss: -3.0,
    duration: '40m',
    screenshotUrl: '',
    screenshots: [],
    entryReason: 'Breakout support trendline di M15.',
    marketContext: 'Pasar berbalik tajam (fakeout) karena berita pound.',
    confirmation: 'Candle close di bawah support.',
    mistake: 'Tidak cek kalender ekonomi sebelum entry.',
    emotion: 'Sedikit kecewa karena kena fakeout.',
    lesson: 'Selalu periksa jadwal rilis data ekonomi.',
    tags: ['#fakeout', '#loss', '#news'],
    executedToPlan: true,
    planViolation: false,
    backtestSessionId: 'BT-2026-09-14-01',
    accountId: 'Backtest Account',
    isDemo: true,
    createdAt: '2026-09-16T09:30:00Z',
  },
];
